### ISSUE TITLE
Use delimited identifiers for column names

### ISSUE THREAD

**Issue by cwitthauer** [GoEddie/MergeUi#1]
If your table has columns with names that contain certain characters such as hyphens, the generated merge statement will have syntax errors. This could be resolved by enclosing the column names in brackets.

**Comment by GoEddie** [comment]
Hi - thanks for this, I am working on a new version and this will be definitely included in it.

The fix will mean all identifiers are quoted [identifier] so will catch spaces as well etc.

**Comment by GoEddie** [comment]
All columns are now quoted within [ and ]:

https://github.com/GoEddie/SSDT-DevPack/blob/master/release/SSDTDevPack.VSPackage.1.0.vsix?raw=true
