### ISSUE TITLE
Persist database connection info for importing data

### ISSUE THREAD

**Issue by cwitthauer** [GoEddie/MergeUi#2]
When importing data into MergeUi from multiple tables, the database connection info must be re-entered for each table. Perhaps the connection info could be persisted to make use of the tool more productive.

**Comment by GoEddie** [comment]
Hi, This is going to be included in the next version as it is really annoying!

Thank you,

ed

**Comment by GoEddie** [comment]
This is now persisted within a visual studio session, I don't save it to disk or anything.

Also there is now a multiple import dialog so you can import more than one table at a time.

https://github.com/GoEddie/SSDT-DevPack/blob/master/release/SSDTDevPack.VSPackage.1.0.vsix?raw=true
